name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        operating-system:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        go-versions:
        - '1.13'
        - '1.14'
    runs-on: ${{ matrix.operating-system }}
    steps:
    - name: Set up Go ${{ matrix.go-versions }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-versions }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        make get
    - name: Lint Code
      run: |
        GOBIN=$PWD/bin go install golang.org/x/tools/cmd/goimports
        GOBIN=$PWD/bin go install golang.org/x/lint/golint
        export PATH=$PATH:$PWD/bin
        make lint
    - name: Test
      run: |
        make test
    - name: Build Artifacts
      run: |
        make build
