on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    name: Build
    strategy:
      matrix:
        operating-system:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        go-versions:
        - '1.14'
    runs-on: ${{ matrix.operating-system }}
    steps:
    - name: Set up Go ${{ matrix.go-versions }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-versions }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build Artifacts
      if: matrix.operating-system != 'windows-latest'
      run: |
        go build -ldflags="-s -w" -o gcb-visualizer
        zip gcb-visualizer-${{ matrix.operating-system }}.zip gcb-visualizer
        rm gcb-visualizer
    - name: Build Artifacts
      if: matrix.operating-system == 'windows-latest'
      run: |
        go build -ldflags="-s -w" -o gcb-visualizer.exe
        compress-archive -destinationpath gcb-visualizer-${{ matrix.operating-system }}.zip -path gcb-visualizer.exe -compressionlevel optimal
        rm gcb-visualizer.exe
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: gcb-visualizer-${{ matrix.operating-system }}.zip
        path: gcb-visualizer-${{ matrix.operating-system }}.zip
  create-release:
    name: Upload
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: gcb-visualizer-ubuntu-latest.zip
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gcb-visualizer-ubuntu-latest.zip
        asset_name: gcb-visualizer.ubuntu.zip
        asset_content_type: application/zip
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: gcb-visualizer-macOS-latest.zip
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gcb-visualizer-macOS-latest.zip
        asset_name: gcb-visualizer.darwin.zip
        asset_content_type: application/zip
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: gcb-visualizer-windows-latest.zip
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gcb-visualizer-windows-latest.zip
        asset_name: gcb-visualizer.windows.zip
        asset_content_type: application/zip
